### ISSUE TITLE
Check if logger work properly

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#127]
I think the oob and inbag logger have some issues in determining when to stop. Additionally, stopping if the process is smaller then an epsylon is too hard, maybe we should say if the last 3 or 5 iterations was smaller then the epsylon, then stop.

**Comment by ja-thomas** [comment]
Add a "patience" parameter, i.e., if no improvement is found for k iterations, stop.

**Comment by schalkdaniel** [comment]
Done :)
