### ISSUE TITLE
C++ predict on newdata could be improved

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#206]
At the moment we iterate over the parameter map which obviously contains as much entries as base-learner. In each iteration we check if the corresonding feature exists within the newdata map.

It would be better to iterate over the newdata and just select the corresponding parameters from the parameter map.

**Comment by SGolbert** [comment]
Hi Daniel, I think there is a bug with BaselearnerPolynomial::predict (std::shared_ptr<data::Data> newdata). It doesn't consider whether there is an intercept or not.

**Comment by schalkdaniel** [comment]
Should be fixed.
