### ISSUE TITLE
Replace for loop in boostLinear and boostSpline with foreach?

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#223]
This could improve performance since it would be very easy to parallelize the base-learner initialization here. Is this worth depending on parallel or foreach?

**Comment by ja-thomas** [comment]
We can do this, but I wouldn't put very high prio on this, since it wouldn't work for the general case and only helps for creating the objects not the actual training.

I think parallelism via parallel evaluation of BLs is much more desirable :)

**Comment by schalkdaniel** [comment]
TRUE :)
