### ISSUE TITLE
naming issue: getters in Compboost

### ISSUE THREAD

**Issue by berndbischl** [schalkdaniel/compboost#235]
what is this exatctly

```
selected
method to get a character vector of selected base-learner.

coef
method to get a list of estimated coefficient for each selected base-learner.
```

is this autogenerated somehow? or handcoded?  should this be an active binding? or start names with "get"?

I am "complaining" beacuse if you look here

```
getBaselearnerNames
method to get names of registered fatories.
```

this is now an inconsisten naming scheme

**Comment by berndbischl** [comment]
does everyone know how active bindings work?

**Comment by ja-thomas** [comment]
Yes, but imo. the main advantage for ABs is that you can have getter and setter in a single function, in our case we only have getter, so a regular function is better.

**Comment by schalkdaniel** [comment]
So, we agree with getter? Moved to #244, updates and comments there.

**Comment by berndbischl** [comment]
hi,
here is our R6 standard, please try to stick to this. we should also write it down at some point:

- member variables that the user might want to access / set are simply public. not getters, or ABs.

- *if* we want to overwrite that, make it more flexible, we create an AB for that member var. with the same name as the var. this allows transparent type conversions in the AB, type checks in setters, and so on. 
we only do this if this is very useful. ABs are ONLY used for member vars.

- for the (more complex) rest we use normal methods, including getters and setters, and they are called doThatThing, start with a verb.

agrred?

**Comment by schalkdaniel** [comment]
A standard would be great, also about class naming, documenting, and (maybe) testing.

**Comment by berndbischl** [comment]
> A standard would be great, also about class naming, documenting, and (maybe) testing.

if you iniate a repo, have the other phds help update that. or you can update my style guide. after that i can iterate

**Comment by schalkdaniel** [comment]
A standard would be great, also about class naming, documenting, and (maybe) testing.
