### ISSUE TITLE
if possible move ggplot2 to SUGGESTS

### ISSUE THREAD

**Issue by berndbischl** [schalkdaniel/compboost#236]
this is a heavy dependency and you dont really need it

**Comment by ja-thomas** [comment]
but everybody has installed it anyways :)

**Comment by berndbischl** [comment]
really not true. i have seen problems on clusters for exactly such a thing....

**Comment by ja-thomas** [comment]
ok, agreed. Should hopefully be only a small change anyways, just require the package in the plot functions. (You can compare what we do in mlr)

**Comment by berndbischl** [comment]
> just require the package in the plot functions.

i hope that works, at least try it

**Comment by schalkdaniel** [comment]
Done in 0414d9c, but I also had to adjust the vignettes since they also need ggplot which isn't loaded when listed as suggests. I have included a flag which doesn't eval code chunks if ggplot isn't installed (130d607). But build is passing now.
