### ISSUE TITLE
Compboost: addBaseLearner doc issue

### ISSUE THREAD

**Issue by berndbischl** [schalkdaniel/compboost#240]
```

For cboost$addBaselearner():

features
[vector(mode = "character")]
Vector of column names which are used within the specified base-learner. Each column is defined as new base-learner by using the learner given by bl.factory.
```

It is unclear what this means. what happens if I specify a PolyBlearner, and degree 1, and 2 features c("V1", "V2")

**Comment by schalkdaniel** [comment]
Sorry for that, we have updated the function without updating the documentation. What happens is that a linear model is fitted with two features V1 and V2 as ONE base-learner. Done: 1060277 and ad2ede3
