### ISSUE TITLE
Polynomial Baselearner

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#31]
Should the polynomial baselearner just create one single new variable e.g. for poly(x, degree = 3) we than just have one variable x^3 or should we include in degree = 3 the first and second degree? The data for the training then is a matrix with (x, x^2, x^3). The second option is implemented at the moment.

**Comment by ja-thomas** [comment]
I think the first version might be better. 
Since we can go from the first version to the second (by creating three baselearners) but not from the second to the first.

We can add a convenience wrapper latter that does the second variant based using the first

**Comment by schalkdaniel** [comment]
You are right! Thats also the easier one to implement. :) 

Done in #32
