### ISSUE TITLE
Baselearner declaration

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#33]
Problem: With the baselearner declaration at the moment (via the constructor) we are very restricted. Imagine a polynomial baselearner which takes the arguments data and degree and a spline baselearner which takes the same arguments. We are not able to create two different constructors with the same parameter list.

**Comment by schalkdaniel** [comment]
This should be fixed by fixing #36.

**Comment by schalkdaniel** [comment]
Ok the issue still exists within the `BaselearnerWrapper`. :(

**Comment by ja-thomas** [comment]
use child classes

**Comment by schalkdaniel** [comment]
This is done in #73. There are now for every factory a class (e.g. `PolynomialFactory`).
