### ISSUE TITLE
installing *source* package 'compboost'

### ISSUE THREAD

**Issue by VladPerervenko** [schalkdaniel/compboost#333]
`devtools::install_github("schalkdaniel/compboost")
Downloading GitHub repo schalkdaniel/compboost@HEAD
√  checking for file 'C:\Users\User\AppData\Local\Temp\RtmpYdSMnE\remotes153c522e20e6\schalkdaniel-compboost-40f0432/DESCRIPTION' (370ms)
-  preparing 'compboost': (13.7s)
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1.2s)
-  checking for empty or unneeded directories
-  building 'compboost_0.1.1.tar.gz'
   
Installing package into ‘C:/Users/User/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'compboost' ...
** using staged installation
** libs
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.4/include" -DNDEBUG  -I'C:/Users/User/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/User/Documents/R/win-library/4.0/RcppArmadillo/include' -I'C:/Users/User/Documents/R/win-library/4.0/BH/include'     -fopenmp   -O3 -march=native -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.4/include" -DNDEBUG  -I'C:/Users/User/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/User/Documents/R/win-library/4.0/RcppArmadillo/include' -I'C:/Users/User/Documents/R/win-library/4.0/BH/include'     -fopenmp   -O3 -march=native -c baselearner.cpp -o baselearner.o
In file included from baselearner.h:28,
                 from baselearner.cpp:21:
data.h:36:10: fatal error: boost/serialization/export.hpp: No such file or directory
 #include <boost/serialization/export.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.4/etc/x64/Makeconf:229: baselearner.o] Error 1
ERROR: compilation failed for package 'compboost'
* removing 'C:/Users/User/Documents/R/win-library/4.0/compboost'
* restoring previous 'C:/Users/User/Documents/R/win-library/4.0/compboost'`

Something went wrong. Where is the problem? Can you tell me?

**Comment by schalkdaniel** [comment]
Hi, yes. It seems like the boost library can not be found by the compiler. But it shouldn't be included in the code anyway. I will work on it and reset the code. I comment here when finished.

**Comment by VladPerervenko** [comment]
`** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (compboost)`
Installed normally now.

**Comment by schalkdaniel** [comment]
Great! I still have to do some fixes and tests. but the core should run normally.
