### ISSUE TITLE
Loss structure

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#5]
The loss structure is at the moment a bit confusing. There are three stages since a loss is created, starting with the loss wrapper which calls the loss constructors which defines a loss and creates a child of the `DefinedLoss` class. Hacky, but very variable. It is possible to remove the step in the middle and directly create the objects within the loss wrapper (for `R`). This takes away the opportunity of a standalone `c++` implementation.

**Comment by ja-thomas** [comment]
Let's talk about this in a bit more detail, I think getting this right is quite important and not super simple
