### ISSUE TITLE
Iterator crashes the system after compilation???

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#62]
E. g. in `compboost.h` in function `GetSelectedBaselearner` and `GetModelFrame` the functions are not useable if we use the iterator (especially the `.end()` member). This looks very odd since for other classes the iterator works?

**Comment by ja-thomas** [comment]
Please always create a reproducible example for this kind of stuff.
Either in the issue or as a test file in the repo

**Comment by schalkdaniel** [comment]
This is caused by the destructor issue #66 and partly fixed in #65.
