### ISSUE TITLE
Constructors are initializing twice

### ISSUE THREAD

**Issue by ja-thomas** [schalkdaniel/compboost#7]
I think you showed me that also at the last meeting, but just so that we don't forget:

```
> lo = LossWrapper$new()
Create new Loss (default: quadratic): 0x1f54720
Create new Loss (default: quadratic): 0x7fff50556ef0
```

**Comment by schalkdaniel** [comment]
This is a pass by value issue and can only be solved by using pass by reference. But this is nothing too bad.
