### ISSUE TITLE
ConstantInitializer

### ISSUE THREAD

**Issue by ja-thomas** [schalkdaniel/compboost#8]
We don't need to create a matrix/vector here.

A single value should be enough since it's constant.

**Comment by schalkdaniel** [comment]
Absolutely, the idea was that armadillo then just have to add vectors. But it should be possible to add a scalar with a vector, so you are right. I will try that.

**Comment by ja-thomas** [comment]
efficient sclar/vector/matrix operations should hopefully all work in armadillo

**Comment by schalkdaniel** [comment]
Done in #15.
