### ISSUE TITLE
avoid ugly switch

### ISSUE THREAD

**Issue by schalkdaniel** [schalkdaniel/compboost#9]
At the moment there is a ugly if switch in the loss.cpp file. This should be avoided.

**Comment by ja-thomas** [comment]
This seems relevant: https://stackoverflow.com/questions/582331/is-there-a-way-to-instantiate-objects-from-a-string-holding-their-class-name

**Comment by schalkdaniel** [comment]
This is now done by exposing all loss classes in #74.
